language: php

sudo: false

addons:
  apt:
    packages:
      - libxml2-utils

branches:
  only:
    - master
    - develop
    - /^[0-9]+\.[0-9]+\.[0-9]+$/

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    - typo3@evoweb.de

install:
  - >
    export TYPO3_PATH_WEB=$PWD/.Build/Web;
    composer require typo3/cms-core="$TYPO3_VERSION" $PREFER_LOWEST;
    if [ ! -z "$TESTING_FRAMEWORK" ]; then composer require --dev typo3/testing-framework="$TESTING_FRAMEWORK"; fi;
    git checkout composer.json;

before_script:
  - phpenv config-rm xdebug.ini

script:
  - >
    echo "Running functional tests -- not implemented jet";
    #export typo3DatabaseName="typo3";
    #export typo3DatabaseHost="localhost";
    #export typo3DatabaseUsername="root";
    #export typo3DatabasePassword="";
    #php .Build/bin/phpunit --colors -c .Build/Web/vendor/typo3/testing-framework/Resources/Core/Build/FunctionalTests.xml Tests/Functional/;

jobs:
  fast_finish: true
  allow_failures:
    - env:
        - TYPO3_VERSION="dev-master as 10.0.0"

  include:
    - &lint
      stage: test
      php: 7.3
      env: TASK="PHP Lint"
      before_install: skip
      install: skip
      before_script: skip
      script:
      - errors=$(find . -name \*.php ! -path "./.Build/*" -exec php -d display_errors=stderr -l {} 2>&1 >/dev/null \;) && echo "$errors" && test -z "$errors"
    - <<: *lint
      php: 7.2

    - stage: test
      php: 7.3
      env:
        - TYPO3_VERSION="^10.0"
    - stage: test
      php: 7.2
      env:
        - TYPO3_VERSION="^10.0"
      before_script: skip
    - stage: test
      php: 7.2
      env:
        - TYPO3_VERSION="dev-master as 10.0.0"

    - stage: publish in ter
      if: tag IS present
      php: 7.1
      before_install: skip
      install: skip
      before_script: skip
      script:
      - |
        if [ -n "$TYPO3_ORG_USERNAME" ] && [ -n "$TYPO3_ORG_PASSWORD" ]; then
          echo -e "Preparing upload of release ${TRAVIS_TAG} to TER\n";

          # Install requirements
          composer global require helhum/ter-client dev-master

          # Cleanup before we upload
          git reset --hard HEAD && git clean -fx

          # Set version number from tag
          sed -i "s/version' => '.*'/version' => '${TRAVIS_TAG}'/" ext_emconf.php

          # Upload
          TAG_MESSAGE=`git tag -n10 -l $TRAVIS_TAG | sed 's/^[0-9.]*[ ]*//g'`
          echo "Uploading release ${TRAVIS_TAG} to TER"
          $HOME/.composer/vendor/bin/ter-client upload ew_socialfeedwall . -u "$TYPO3_ORG_USERNAME" -p "$TYPO3_ORG_PASSWORD" -m "$TAG_MESSAGE"
        fi;
